### PR TITLE
Suggested edits to update the Homepage

### PR DESCRIPTION
**Pull request by rroberge**
@jonathanbaker, @johnwunder, @sbarnum, @bschmoker

Not sure why preview doesn't look like live site, but:
(1) Changed site title to fully spelled-out STIX name, as discussed at the f-2-f.
(2) Removed the 3 training promo items, as discussed at the f-2-f.
(3) Added items for Version 1.2 upcoming release; Version 1.1.1. current release (to be replaced with Community once v1.2 is live); and OASIS, with a link to the Announcement doc since the FAQ is linked above.
(4) Changed the mailto link to 'stix@mitre.org' (at the f-2-f, Rich said he doesn't monitor the other email account).
(5) STILL NEEDED:  addition of the new STIX logo.

### CODE REVIEW

**Comment by bschmoker** [comment]
@rroberge - the markdown preview doesn't render CSS / JS which we use on the live site. You can see [a preview here](https://bschmoker.github.io/) 

1 - :heavy_check_mark: , made a bit smaller to fit on one line in my commit
2 - :heavy_check_mark: 
3 - :x: I'd prefer the current approach, a link to /release  (download button), which points to 1.1.1, can be redirected to 1.2 once it's production-ready
4 - :heavy_check_mark: 
5 - suggest adding to top left as 100x200px-ish http://stix.mitre.org/images/logov3.png

**Comment by rroberge** [comment]
Thanks @bschmoker  

Yes, that is the logo we should add. I wasn't sure how to upload it in markdown?

Once we add the STIX logo, maybe we could remove the (STIX tm) if we put the logo at the beginning of the title row?

Regarding:
>3 - :x: I'd prefer the current approach, a link to /release (download button), which points to 1.1.1, can be redirected to 1.2 once it's production-ready

I'm not against that approach, I was just following how we promoted Community engagement for upcoming releases on the old stix.mitre.org site.  If we only have the Current Language Release item as you propose, we can easily make that Upcoming Language Release item Ibe an item for Community instead, as I suggested we would be doing shortly on 5/15 anyway once v1.2 is live. So it would have only been like this for 2-1/2 weeks until we changed it, but if everyone is okay with not promoting v1.2 we can do it now no problem.

I also noticed an extra character space that needs to be fixed in the text I added in the News blog item.

Bob

**Comment by bschmoker** [comment]
Cool, so we would add the logo to /images, and add to the header CSS

Not sure I understand the concern about promotion on (3) :question:

**Comment by johnwunder** [comment]
tbh I don't think we need a top-level item for STIX 1.2. The people that need to know about it are on the mailing list, newbies should probably not be getting involved w/ development versions anyway. That frees up the middle section for idioms, which I think should stay.

I also would rather have the links be very obviously for the current version...i.e. don't say "STIX 1.1.1" say "Current Release" or something.

**Comment by bschmoker** [comment]
@rroberge [The link on this line]https://github.com/STIXProject/stixproject.github.io/pull/226/files#diff-d680e8a854a7cbad6d490c445cba2ebaR24) should point to `/release` instead

**Comment by bschmoker** [comment]
@rroberge please merge this PR into your fork's branch https://github.com/rroberge/stixproject.github.io/pull/6 and everything will be fine

**Pull request merged**
