### PR TITLE
Added 1 new from Invincea & 1 new from AlienVault

### PR DESCRIPTION
**Pull request by rroberge**
@johnwunder, @bschmoker

Added AlienVault under User Community and Invincea under Products/Services.

### CODE REVIEW

**Comment by bschmoker** [comment]
@rroberge Thanks! :shipit: Looks good to merge to me

**Comment by gtback** [comment]
Is there a reason hailataxii was removed as part of this commit? Just wanted to make sure it was intentional before I merged this, since it's not mentioned in the discussion.

**Comment by bschmoker** [comment]
@gtback - nice catch, looks like it was actually [in there twice](https://github.com/STIXProject/stixproject.github.io/pull/252/files#diff-4e5b2a8ea5ca0cbfc262944c75be1ceaL19) - so removing the dupe is OK

**Comment by rroberge** [comment]
@gtback @bschmoker  - Sorry about that. I removed that dupe before I did the markdown for the new products and forgot to include it once I was done wit the others. Last week we merged some older additions from when I first started doing these that hadn't been merged yet, and somehow hailataxii duped in the Communities section when we did so I deleted it.

**Comment by rroberge** [comment]
I will merge it now.

**Pull request merged**
