### PR TITLE
add /release

### PR DESCRIPTION
**Pull request by bschmoker**

### CODE REVIEW

**Comment by gtback** [comment]
Should you also parameterize the version number in the file name? Also, Can you replace the link in the page text with `{{ page.redirect_to }}`?

**Comment by bschmoker** [comment]
@gtback thanks for the suggestion, missed those 

Will build first to make sure the liquid vars get picked up on render

**Comment by johnwunder** [comment]
Can somebody explain why we need this page? I don't get it?

**Comment by gtback** [comment]
I assumed it was so it would be easier to link directly to the download page for the latest release based on `site.current_version`. I could be mistaken though.

**Comment by johnwunder** [comment]
Yeah I thought we had a redirect on the main site to go to the current version but it seems like we don't.

**Pull request merged**
