### PR TITLE
add /community and /news to navbar header

### PR DESCRIPTION
**Pull request by bschmoker**
> from @rroberge 
As discussed at today's meeting, I added main menu nav items for "Community" and "News". I am working on the News archives pages now, so under News will soon be a drop-down so visitors can access the historical items in the news archives pages transferred from stix.mitre.org.

@bschmoker, did I do the above correctly?   Also, is below how to do a drop-down for example under "About" to add a quick link to the 'FAQs'?

       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">About<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li role="presentation"><a href="/about/#frequently-asked-questions">FAQs</a></li>
         </ul>
        </li>

### CODE REVIEW

**Comment by bschmoker** [comment]
Looks like the CSS is a bit off, will make a commit to have it look the same

**Comment by bschmoker** [comment]
You have it right on the /about link, though I would push back against making it a dropdown since it's much more common to have a 'single click about button' design

**Comment by rroberge** [comment]
Thanks @bschmoker, I was attempting to follow the CSS of our existing nav bar when I added the new items. Where did I screw up?
Also, sorry it wasn't more clear but I was just using the "About" one as an example to see if I did it correctly for when I eventually add the News Archives pages. That's why I only put it in the comments, but obviously I should have explained that better. And I do agree in this instance it's not really necessary for the minimal FAQs we have (also we have OASIS FAQs too, so adding another FAQs link in the site never would be not be good UX). But I would add that dropdowns are still very widely used. Thanks again.

**Comment by bschmoker** [comment]
Nah you didn't 'screw up' :smile_cat: the `ul` just needed to be below the new entries as in https://github.com/STIXProject/stixproject.github.io/commit/b47aecc228ce628e24f83a8210492e1f673ed150#diff-70c103dc160c67e7a579206a58d26b94R83

**Comment by rroberge** [comment]
Thanks @bschmoker, I see now what I did wrong.  This looks okay to me to merge, but can we make part of this pull request that the STIX Logo in the nav bar always goes to the main stixproject.github.io/ homepage? (Right now it just reloads page you are on.)  Or does that need to be a separate pull request? Thanks again.

**Comment by bschmoker** [comment]
huh, it was set to `site.root` which *should* have been the base URL, but instead is an empty string
i.e.
```
<a href="" class="pull-left"><img src="/images/logo.png" 
```

I hard-coded it in the commit, since `site.baseurl` was also just an empty string cc @gtback

**Comment by rroberge** [comment]
Okay to merge?

**Comment by bschmoker** [comment]
cool for me, would defer to @johnwunder on whether it looks good

**Comment by johnwunder** [comment]
I see two links with `href="TODO"`...

**Comment by rroberge** [comment]
We should omit those 2 href="TODO" for now.

**Comment by bschmoker** [comment]
Oh yeah @rroberge those were placeholders for you to add the archives link

**Comment by rroberge** [comment]
I added a new commit to delete them for the time being. Are we good to go?

**Comment by johnwunder** [comment]
There were a few bugs in this:

* Missing the caret to indicate that the item was a dropdown
* Both items in the list went to stixproject.tumblr.com

I fixed them and merged master, so merging this now.

**Comment by bschmoker** [comment]
i was like 'why is dd9f76f so huge' and then 'oh yeah it merged master T_T

**Comment by johnwunder** [comment]
Haha yeah I had the same thought when I went to do the commit. "Holy crap that's a lot of changes, all this does is add a menu! Oh, yeah..."

**Pull request merged**
