### PR TITLE
update examples for 1.2

### LINKED ISSUE #238: All idioms need to be updated
For each idiom:

1. Review for whether it uses deprecated fields, if so update to not do that
2. Update the version number of the `STIX_Package` construct

### PR DESCRIPTION
**Pull request by bschmoker**
closes #238 

Builds cleanly [using the 1.2 validator](https://travis-ci.org/bschmoker/stixproject.github.io/builds/62124925) as configured in (now rebased out) [travis config](https://github.com/bschmoker/stixproject.github.io/commit/63aea16e5c03774311cbc8486fc5c28f4b7654e0?diff=split)

:exclamation: will fail to build against this branch, since it's not using the same travis config

cc:@stixproject

### CODE REVIEW

**Comment by bschmoker** [comment]
I'll fix the merge conflicts against `1.2`

**Comment by johnwunder** [comment]
This is looking pretty closed, just:

- All version numbers on STIX_Package need to be updated to 1.2
- All schema locations need to be updated to 1.2

You also reminded me that `@timestamp` on `STIX_Package` is deprecated. I need to go back through the samples and make sure it's removed because I don't think I did it the first time.

**Comment by bschmoker** [comment]
Yep, looks like the merge conflicts are that the ver # needs bumped (which you had done previously)

**Comment by bschmoker** [comment]
@johnwunder - checks are being run on https://github.com/bschmoker/stixproject.github.io/pull/2 to make sure I didn't break anything in the merge

**Pull request merged**
