### PR TITLE
add /community page

### PR DESCRIPTION
**Pull request by rroberge**
@jonathanbaker, @johnwunder, @sbarnum, @bschmoker

As part of this I recommend adding "Community" as a menu item in the Main Site Navigation to the right of "About". I also recommend "Supporters" be a drop-down item under the new "Community" menu item, so visitors can go directly to that page from the main site nav without having to scroll down the Community page to find it.

Finally, I wasn't sure if the 'OASIS Transition' section of this page should have a time frame mentioned, or just leave it to the announcement & faq? I used May 2015 in two places above so it was in there but not too specific in case the actual dates move at all, but this could be deleted if you prefer.

What do you think?
-Bob

### CODE REVIEW

**Comment by bschmoker** [comment]
Hmm, how about adding a section in /about for the #oasis stuff, and putting the mailing list links on the bottom of main landing page under Support?

**Comment by rroberge** [comment]
Hi Ben, "Community" is a keyword people look for on websites today, and having all our community info located on a single Community page goes to ease-of-use since visitors won't have to search around for it, it will all be there consolidated for them in a single location.

**Comment by bschmoker** [comment]
From the SEO angle, if we put the word 'community' on the landing page a few times it should bump it to the top result.
Personally I'd rather have people hit the landing page than a side page

**Comment by rroberge** [comment]
Perhaps more important than SEO as I had initially mentioned is good UX. I left out of my original note that Community participation is a key feature of STIX, so having it as its own page with an item in the top nav bar would make it extremely easy for visitors to find, while also continuing to help us emphasize that key aspect of STIX because it would always be above the fold and visible in the main nav bar.

**Comment by johnwunder** [comment]
I think we should do this. Once we transition to OASIS we can use this page to describe how to contribute via that as well as highlight supporters and open source projects. Any issues w/ merging as-is?

**Comment by rroberge** [comment]
Thanks @johnwunder, I was thinking the exact same thing. The page will need to be revised with additional OASIS info once we have fully transitioned.

**Comment by johnwunder** [comment]
It looks like we have a STIX community section on the about page as well? Should that go away if we merge this page?

**Comment by bschmoker** [comment]
Nah I would just keep that, since people will want/need to see it a bunch of times to actually parse it

**Comment by rroberge** [comment]
I agree with @bschmoker.  Also, having that small section on the About page helps to promote the Community-participation feature of STIX on the page where we summarize the overall effort.

**Comment by johnwunder** [comment]
Works for me, merging.

**Pull request merged**
