### PR TITLE
add retail-isac and others

### PR DESCRIPTION
**Pull request by bschmoker**
Based on @rroberge 's [fork here](https://github.com/rroberge/stixproject.github.io/pull/2)

### CODE REVIEW

**Comment by rroberge** [comment]
@bschmoker, I recommend closing this pull request. I will open a new one to add the (1) FS-ISCA/DTCC, and the (2) Retail-ISAC, to the "User Communities" section, which are the only two things in it that need to be added at this point. I fixed all those other items in subsequent pull requests as I got better at doing them.

|Retail Cyber Intelligence Sharing Center (R-CISC) Intelligence Sharing Portal|[Retail Information Sharing and Analysis Center (FS-ISAC)](http://www.rila.org/rcisc/RetailISAC/Pages/default.aspx/)|Intelligence Sharing Portal managed by the Financial Services Information Sharing and Analysis Center (FS-ISAC)|&#x2713;|&#x2713;|[Press Release](http://www.rila.org/news/topnews/Pages/Retail-ISAC-Launches-Cyber-Sharing-Portal-Supported-by-FS-ISAC.aspx/), [News Article](http://blogs.bromium.com/2015/03/27/retailers-check-out-intelligence-sharing-platform/)|

|[Soltra Edge](http://www.soltraedge.com/)|[Financial Services Information Sharing and Analysis Center (FS-ISAC)](http://www.fsisac.com/), [The Depository Trust & Clearing Corporation (DTCC)](http://www.dtcc.com/), and [Soltra](http://www.soltra.com/)|Soltra is an FS-ISAC and DTCC joint venture created to help secure critical infrastructure entities from cyber threats via its Soltra Edge threat intelligence sharing platform|&#x2713;|&#x2713;|[Press Release](http://www.fsisac.com/sites/default/files/news/FINAL2%20Soltra%20Edge%20GA%20press%20release_12%203%2014WEB2.pdf)|

**Comment by bschmoker** [comment]
@rroberge This PR should be adding those two entries, check the 'View' button to confirm

**Comment by rroberge** [comment]
@bschmoker 
Yes, I do realize that, but I am worried that it is also going to make all those other old edits too. Many of those old edits have already been updated with newer info in the subsequent weeks, and I want to avoid replacing up-to-date info with what may be old info.

**Comment by bschmoker** [comment]
Ah I understand that concern - the way that github works is that you 'merge' the changes into the new file, so everything that's currently live will be fine.

Don't believe me? [check this out](https://github.com/STIXProject/stixproject.github.io/compare/add-isac-vendor)

**Comment by rroberge** [comment]
It was primarily the old urls that would replace the newer urls that are on the live page now.

**Comment by bschmoker** [comment]
@rroberge I'm confused, new URLs? 

The [rendered file](https://github.com/STIXProject/stixproject.github.io/blob/add-isac-vendor/supporters/index.md) is exactly how it will appear, if the URLs are wrong then we can re-fix those

**Comment by rroberge** [comment]
@bschmoker, I believe I changed some of the reference urls in subsequent updates to go to more recent references. But you are right, those can be fixed later if they become an issue. I will merge it now.

**Pull request merged**
