### PR TITLE
Added 4 new products

### PR DESCRIPTION
**Pull request by rroberge**
@bschmoker, @johnwunder, @jonathanbaker

Added BCMS's FLARE from their discussion list message today, BlueCoat's Malware Analysis Appliance submission to the google form, and  FreeSTIX and FreeTAXII from the google form.

### CODE REVIEW

**Comment by bschmoker** [comment]
Should we merge freestix and freetaxii into one row with hyperlink to each one?

**Comment by johnwunder** [comment]
I brought that up for Intelworks and the consensus was to just add them as they get sent in (i.e. keep as two rows).

**Comment by rroberge** [comment]
We are allowing submitters to have individual product listings, so I believe they should stay separate.

**Comment by bschmoker** [comment]
Hmm, I would contend that it's a better user experience to do 'one vendor, one line', but don't feel strongly enough to block :shipit:

**Comment by rroberge** [comment]
Hi Ben, In our email thread discussion on this topic the other week we determined that since vendors see this page an an opportunity to assist in marketing their individual products to the public, which is also the target audience for this page, we would allow the vendors to list each product in the manner in which they are marketing them, i.e., individually. As such, the list itself is set-up by product name and not by organization name. I can forward you the thread if you would like to read the full discussion?

**Pull request merged**
