### PR TITLE
address #66

### PR DESCRIPTION
**Pull request by bschmoker**
@gtback  add a bit of social media info to 'threat actor identity'

### CODE REVIEW

**Comment by gtback** [comment]
I tried to add the information to the PPT->PNG image, but for some reason the image is a lot bigger than before. @johnwunder, do you have any ideas?

**Comment by gtback** [comment]
The new data also needs to be added to the `XML` tab in index.md.

**Comment by johnwunder** [comment]
I originally converted the PPT=>PNG via copy/pasting the content from Powerpoint into Paint. Now I'm on a Mac so can't do that.

We need to make sure the XML is updated before we merge.

**Comment by bschmoker** [comment]
I'll update the XML, and scale the image down to where it was previously

**Comment by bschmoker** [comment]
@johnwunder can merge if passes

**Pull request merged**
