### PR TITLE
Add link to Community main page to Community dropdown menu

### PR DESCRIPTION
**Pull request by rroberge**
@johnwunder, I recommend adding a link to the main /community page in the main site nav in the Community drop-down menu.

### CODE REVIEW

**Comment by bschmoker** [comment]
looks good, added a divider to mirror the other dropdowns

The 'STIX/TAXII Supporters' bit isn't very clear, rephrase [to something like "users"](https://www.docker.com/resources/usecases/) ?

**Comment by johnwunder** [comment]
+1 to users. Supporters sounds like a cheerleading section.

**Comment by rroberge** [comment]
@bschmoker I totally agree it is not obvious what is meant by 'Supporters'. How about "Products & Communities"?  
Other options:
  Products & Communities Using STIX/TAXII
  STIX/TAXII Adopters

**Comment by rroberge** [comment]
Are the vendors the users or are the users of the products/services that incorporate STIX and TAXII the users?

**Comment by johnwunder** [comment]
I think both are the users. The vendors use it in their products and the users of the products/services use it via the vendors.

I'm OK with Adopters but Users seems much more straightforward.

**Comment by rroberge** [comment]
Sounds good. I just made the commit. Are we changing the page title & url too, or just the phrasing in this drop-down menu?

**Comment by johnwunder** [comment]
Let's leave everything else.

**Comment by bschmoker** [comment]
looks cool :shipit:

**Comment by rroberge** [comment]
It looks like the title of the http://stixproject.github.io/supporters/ page has been changed to remove TAXII from the title. Wasn't it decided that there would be 3 pages, a combined STIX/TAXII page that would also be linked to from the TAXII github.io site, and then individual pages for the CybOX and MAEC and github.io sites?

CybOX
MAEC

**Pull request merged**
